package com.epam.gm.services;

import java.sql.SQLException;
import java.util.List;

import org.junit.BeforeClass;
import org.junit.Ignore;
import org.junit.Test;

import com.epam.gm.model.Photo;

public class PhotoServiceTest {
    
    private static PhotoService photoService;
   

    @BeforeClass
    public static void setUpBeforeClass() throws Exception {
	photoService = new PhotoService();
    }
 
@Ignore
    @Test
    public void testGetAllPhotosForUsers() throws SQLException {
	List<Photo> list = photoService.getUserPhotos(8);
	for (Photo photo : list) {
	    System.out.println(photo);
	}
    }
    @Ignore
    @Test
    public void testGetAllPhotosForEvents() throws SQLException {
	List<Photo> list = photoService.getEventPhotos(5);
	for (Photo photo : list) {
	    System.out.println(photo);
	}
    }
    
    @Test
    public void save (){
	Photo photo = new Photo();
	photo.setPath("pathtophoto");
	photo.setOwnerId(5);
	photo.setOwnerType("event");
	Integer id =null;
	try {
	    id = photoService.savePhotoReturnId(photo);
	} catch (IllegalArgumentException | IllegalAccessException
		| SQLException e) {

	    e.printStackTrace();
	}
	System.out.println(" *** autogenerated id : "+id + "  ***"+photo);
    }
    
 

}
