package com.epam.gm.olgmaks.absractdao.model;

import com.epam.gm.olgmaks.absractdao.annotation.AutoGenerated;
import com.epam.gm.olgmaks.absractdao.annotation.Column;
import com.epam.gm.olgmaks.absractdao.annotation.OneToMany;
import com.epam.gm.olgmaks.absractdao.annotation.Entity;

@Entity("car")
public class Car {

    @Column("id")
    @AutoGenerated
    private Integer id;

    @Column("brand_name")
    private String brandName;

    @Column("model_name")
    private String modelName;

    @Column("price")
    private Double price;

    @Column("owner_id")
    private Integer ownerId;

    @OneToMany(Owner.class)
    private Owner owner;

    @Column("driver_id")
    private Integer driverId;

    @OneToMany(Driver.class)
    private Driver driver;

    public Integer getId() {

        return id;
    }

    public void setId(Integer id) {

        this.id = id;
    }

    public String getBrandName() {

        return brandName;
    }

    public void setBrandName(String brandName) {

        this.brandName = brandName;
    }

    public String getModelName() {

        return modelName;
    }

    public void setModelName(String modelName) {

        this.modelName = modelName;
    }

    public Double getPrice() {

        return price;
    }

    public void setPrice(Double price) {

        this.price = price;
    }

    public Integer getOwnerId() {
        return ownerId;
    }

    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    public Owner getOwner() {
        return owner;
    }

    public void setOwner(Owner owner) {
        this.owner = owner;
    }

    @Override
    public String toString() {
        return "Car{" +
                "id=" + id +
                ", brandName='" + brandName + '\'' +
                ", modelName='" + modelName + '\'' +
                ", price=" + price +
                ", ownerId=" + ownerId +
                ", owner=" + owner +
                ", driverId=" + driverId +
                ", driver=" + driver +
                '}';
    }
}
