package com.epam.gm.olgmaks.absractdao.model;

import com.epam.gm.olgmaks.absractdao.annotation.AutoGenerated;
import com.epam.gm.olgmaks.absractdao.annotation.Column;
import com.epam.gm.olgmaks.absractdao.annotation.Entity;
import com.epam.gm.olgmaks.absractdao.annotation.ForeignKey;

/**
 * Created by OLEG on 09.06.2015.
 */
@Entity("driver")
public class Driver {

    @AutoGenerated
    @Column("id")
    @ForeignKey("driver_id")
    private Integer id;

    @Column("f_name")
    private String firstName;

    @Column("l_name")
    private String lastName;

    public Driver(){}

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Override
    public String toString() {
        return "Driver{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                '}';
    }
}
