package com.epam.gm.olgmaks.absractdao.model;

import com.epam.gm.olgmaks.absractdao.annotation.AutoGenerated;
import com.epam.gm.olgmaks.absractdao.annotation.Column;
import com.epam.gm.olgmaks.absractdao.annotation.ForeignKey;
import com.epam.gm.olgmaks.absractdao.annotation.Entity;

/**
 * Created by OLEG on 09.06.2015.
 */
@Entity("role")
public class Role {

    @AutoGenerated
    @Column("id")
    @ForeignKey("role_id")
    private Integer id;

    @Column("name")
    private String name;

    public Role() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "Role{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}
