package com.epam.gm.model;

import com.epam.gm.olgmaks.absractdao.annotation.*;

/**
 * Created by OLEG on 16.06.2015.
 */
@Entity("friend_user")
public class FriendUser {

    @AutoGenerated
    @Column("id")
    private Integer id;

    @Column("user_id")
    private Integer userId;

    @Column("friend_id")
    private Integer friendId;

    @ForeignKey
    @OneToMany(field = "user_id", value = User.class)
    private User user;

    @ForeignKey
    @OneToMany(field = "friend_id", value = User.class)
    private User friend;

    public FriendUser() {
    }

    public FriendUser(Integer userId, Integer friendId) {
        this.userId = userId;
        this.friendId = friendId;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getFriendId() {
        return friendId;
    }

    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public User getFriend() {
        return friend;
    }

    public void setFriend(User friend) {
        this.friend = friend;
    }

    @Override
    public String toString() {
        return "FriendUser{" +
                "id=" + id +
                ", userId=" + userId +
                ", friendId=" + friendId +
                ", user=" + user +
                ", friend=" + friend +
                '}';
    }
}
