package com.epam.gm.model;

import java.util.Comparator;

import com.epam.gm.olgmaks.absractdao.annotation.*;

/**
 * @author user
 */
@Entity("User")
public class User {

    @AutoGenerated
    @Column("id")
    private Integer Id;
    @Column("last_name")
    private String lastName;
    @Column("first_name")
    private String firstName;
    @Column("email")
    private String email;
    @Column("sex")
    private String sex;
    @Column("user_type_id")
    private Integer userTypeId;

    @ForeignKey
    @OneToMany(field = "user_type_id", value = UserType.class)
    private UserType userType;
    @Column("lang_id")
    private Integer langId;

    @ForeignKey
    @OneToMany(field = "lang_id", value = Language.class)
    private Language lang;
    @Column("cell_number")
    private String cellNumber;
    @Column("facebook_id")
    private String facebookId;
    @Column("vk_id")
    private String vkId;
    @Column("is_active")
    private Boolean isActive;
    @Column("address_id")
    private Integer addressId;

    @ForeignKey
    @OneToMany(field = "address_id", value = Address.class)
    private Address address;
    @Column("password")
    private String password;
    
    @Column("avatar_id")
    private Integer avatarId = 10;

    @ForeignKey
    @OneToMany(field = "avatar_id", value = Photo.class)
    private Photo avatar;
    
    private Double points;

    public Integer getId() {
        return Id;
    }

    public void setId(Integer id) {
        Id = id;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public Integer getLangId() {
        return langId;
    }

    public void setLangId(Integer langId) {
        this.langId = langId;
    }

    public String getCellNumber() {
        return cellNumber;
    }

    public void setCellNumber(String cellNumber) {
        this.cellNumber = cellNumber;
    }

    public String getFacebookId() {
        return facebookId;
    }

    public void setFacebookId(String facebookId) {
        this.facebookId = facebookId;
    }

    public String getVkId() {
        return vkId;
    }

    public void setVkId(String vkId) {
        this.vkId = vkId;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    public Integer getAddressId() {
        return addressId;
    }

    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getUserTypeId() {
        return userTypeId;
    }

    public void setUserTypeId(Integer userTypeId) {
        this.userTypeId = userTypeId;
    }

    public UserType getUserType() {
        return userType;
    }

    public void setUserType(UserType userType) {
        this.userType = userType;
    }

    public Language getLang() {
        return lang;
    }

    public void setLang(Language lang) {
        this.lang = lang;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public Integer getAvatarId() {
        return avatarId;
    }

    public void setAvatarId(Integer avatarId) {
        this.avatarId = avatarId;
    }

    public Photo getAvatar() {
        return avatar;
    }

    public void setAvatar(Photo avatar) {
        this.avatar = avatar;
    }
    
	public Double getPoints() {
		return points;
	}

	public void setPoints(Double points) {
		this.points = points;
	}
	
	public static final Comparator<User> BY_POINTS = new Comparator<User>() {
		@Override
		public int compare(User first, User second) {
			return second.points.compareTo(first.points);
		}
	};		
	
	
    @Override
    public String toString() {
        return "User{" +
                "Id=" + Id +
                ", lastName='" + lastName + '\'' +
                ", firstName='" + firstName + '\'' +
                ", email='" + email + '\'' +
                ", sex='" + sex + '\'' +
                ", userTypeId=" + userTypeId +
                ", userType=" + userType +
                ", langId=" + langId +
                ", lang=" + lang +
                ", cellNumber='" + cellNumber + '\'' +
                ", facebookId='" + facebookId + '\'' +
                ", vkId='" + vkId + '\'' +
                ", isActive=" + isActive +
                ", addressId=" + addressId +
                ", address=" + address +
                ", password='" + password + '\'' +
                ", avatarId=" + avatarId +
                ", avatar=" + avatar +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        User user = (User) o;

        if (Id != null ? !Id.equals(user.Id) : user.Id != null) return false;
        if (email != null ? !email.equals(user.email) : user.email != null) return false;
        if (firstName != null ? !firstName.equals(user.firstName) : user.firstName != null) return false;
        if (lastName != null ? !lastName.equals(user.lastName) : user.lastName != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = Id != null ? Id.hashCode() : 0;
        result = 31 * result + (lastName != null ? lastName.hashCode() : 0);
        result = 31 * result + (firstName != null ? firstName.hashCode() : 0);
        result = 31 * result + (email != null ? email.hashCode() : 0);
        return result;
    }
}
