package com.epam.gm.model;

import java.util.Date;

import com.epam.gm.olgmaks.absractdao.annotation.AutoGenerated;
import com.epam.gm.olgmaks.absractdao.annotation.Column;
import com.epam.gm.olgmaks.absractdao.annotation.Entity;
import com.epam.gm.olgmaks.absractdao.annotation.ForeignKey;
import com.epam.gm.olgmaks.absractdao.annotation.OneToMany;

@Entity("walletupdate")
public class WalletUpdate {
	@AutoGenerated
	@Column("id")
	private Integer id;
	@Column("user_id")
	private Integer user_id;
	@Column("sum")
	private Integer sum;
	@Column("transaction")
	private Integer transaction;
	@Column("date")
	private Date date;
	@Column("wallet_id")
	private Integer wallet_id;

	@ForeignKey
	@OneToMany(field = "user_id", value = User.class)
	private User user;

	@ForeignKey
	@OneToMany(field = "wallet_id", value = Wallet.class)
	private Wallet wallet;

	public Wallet getWallet() {
		return wallet;
	}

	public void setWallet(Wallet wallet) {
		this.wallet = wallet;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public Integer getSum() {
		return sum;
	}

	public void setSum(Integer sum) {
		this.sum = sum;
	}

	public Integer getTransaction() {
		return transaction;
	}

	public void setTransaction(Integer transaction) {
		this.transaction = transaction;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Override
	public String toString() {
		return "WalletUpdate [id=" + id + ", user_id=" + user_id + ", sum="
				+ sum + ", transaction=" + transaction + ", date=" + date
				+ ", wallet_id=" + wallet_id + ", user=" + user + ", wallet="
				+ wallet + "]";
	}

}
